[phases.setup]
nixPkgs = ['python312', 'gcc', 'libpq']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements-railway.txt']

[start]
cmd = 'python src/main.py -m http -p ${PORT:-8000}'
